services:

    algoritma_test.listener.js_logger_subscriber:
        class: 'Algoritma\BehatExtension\Listener\JsLogSubscriber'
        arguments:
            - '@mink'
            - '%kernel.log_dir%'
        tags:
            - { name: 'event_dispatcher.subscriber' }

    algoritma_element_factory:
        class: 'Algoritma\BehatExtension\Element\AlgoritmaElementFactory'
        arguments:
            - '@mink'
            - '@mink.selectors_handler'
            - []
        tags:
            - { name: 'suite_aware' }

    algoritma_page_factory:
        class: 'Algoritma\BehatExtension\Element\AlgoritmaPageFactory'
        arguments:
            - '@algoritma_element_factory'
            - []

    algoritma_behat_page_object_initializer:
        class: 'Algoritma\BehatExtension\Context\Initializer\AlgoritmaPageObjectInitializer'
        arguments:
            - '@algoritma_element_factory'
            - '@algoritma_page_factory'
        tags:
            - { name: 'context.initializer' }

    algoritma_behat_session_alias_provider:
        class: Algoritma\BehatExtension\Context\SessionAliasProvider

    algoritma_behat_session_alias_initializer:
        class: 'Algoritma\BehatExtension\Context\Initializer\SessionAliasAwareInitializer'
        arguments:
            - '@algoritma_behat_session_alias_provider'
        tags:
            - { name: 'context.initializer' }

    algoritma_behat_browser_tab_manager:
        class: Algoritma\BehatExtension\Context\BrowserTabManager

    algoritma_behat_browser_tab_manager_initializer:
        class: 'Algoritma\BehatExtension\Context\Initializer\BrowserTabManagerAwareInitializer'
        arguments:
            - '@algoritma_behat_browser_tab_manager'
        tags:
            - { name: 'context.initializer' }

    Doctrine\Inflector\Inflector:
        factory: [ !service { class: Doctrine\Inflector\Rules\English\InflectorFactory }, 'build' ]

    Algoritma\BehatExtension\Context\Initializer\AppKernelInitializer:
        arguments:
            - '@fob_symfony.kernel'
        tags:
            - { name: 'context.initializer' }

    algoritma_test.storage.failed_features:
        class: Algoritma\BehatExtension\Storage\FailedFeatures
